replicaCount: 1

auth:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 1

controller:
  replicaCount: 0 

kraft:
  enabled: false  

listeners:
  client:
    protocol: PLAINTEXT
  interBroker:
    protocol: PLAINTEXT

externalAccess:
  enabled: false
