apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: education
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
    spec:
      containers:
        - image: chinhval/educationgatewayservice
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 80
          env:
            - name: ReverseProxy__Routes__identityservice__ClusterId
              value: identityservice
            - name: ReverseProxy__Routes__identityservice__Match__Path
              value: /identityservice/{**catch-all}
            - name: ReverseProxy__Routes__identityservice__Transforms_0__PathRemovePrefix
              value: /identityservice
            - name: ReverseProxy__Routes__identityservice__Transforms_1__PathPrefix
              value: /

            - name: ReverseProxy__Routes__trainingservice__ClusterId
              value: trainingservice
            - name: ReverseProxy__Routes__trainingservice__Match__Path
              value: /trainingservice/{**catch-all}
            - name: ReverseProxy__Routes__trainingservice__Transforms_0__PathRemovePrefix
              value: /trainingservice
            - name: ReverseProxy__Routes__trainingservice__Transforms_1__PathPrefix
              value: /

            - name: ReverseProxy__Routes__studentservice__ClusterId
              value: studentservice
            - name: ReverseProxy__Routes__studentservice__Match__Path
              value: /studentservice/{**catch-all}
            - name: ReverseProxy__Routes__studentservice__Transforms_0__PathRemovePrefix
              value: /studentservice
            - name: ReverseProxy__Routes__studentservice__Transforms_1__PathPrefix
              value: /

            - name: ReverseProxy__Routes__registerservice__ClusterId
              value: registerservice
            - name: ReverseProxy__Routes__registerservice__Match__Path
              value: /registerservice/{**catch-all}
            - name: ReverseProxy__Routes__registerservice__Transforms_0__PathRemovePrefix
              value: /registerservice
            - name: ReverseProxy__Routes__registerservice__Transforms_1__PathPrefix
              value: /

            - name: ReverseProxy__Clusters__identityservice__ClusterId
              value: identityservice
            - name: ReverseProxy__Clusters__identityservice__Destinations__destination1__Address
              value: http://identity

            - name: ReverseProxy__Clusters__trainingservice__ClusterId
              value: trainingservice
            - name: ReverseProxy__Clusters__trainingservice__Destinations__destination1__Address
              value: http://training

            - name: ReverseProxy__Clusters__studentservice__ClusterId
              value: studentservice
            - name: ReverseProxy__Clusters__studentservice__Destinations__destination1__Address
              value: http://student

            - name: ReverseProxy__Clusters__registerservice__ClusterId
              value: registerservice
            - name: ReverseProxy__Clusters__registerservice__Destinations__destination1__Address
              value: http://register       
              
        
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: education
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway