apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Chinh00/Education
    targetRevision: HEAD
    path: deployments/infra/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
