apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: education
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4317   # OTLP gRPC
            - containerPort: 4318   # OTLP HTTP
            - containerPort: 14250  # gRPC collector
            - containerPort: 14268  # HTTP collector
            - containerPort: 16686  # Web UI
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: education
spec:
  selector:
    app: jaeger
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: grpc-collector
      port: 14250
      targetPort: 14250
    - name: http-collector
      port: 14268
      targetPort: 14268
    - name: ui
      port: 16686
      targetPort: 16686
  type: ClusterIP
