name: 🚀 Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  main:
    name: 📦 Build and Push Services
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Context
        uses: actions/checkout@v4

      - name: 🛠️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🏗️ Build and push Docker image Identity Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Gateways/Gateway/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_EDUCATION_GATEWAY_SERVICE}}:latest