name: 🚀 Build sinhvien client

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: 📦 Build and Push Services
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Context
        uses: actions/checkout@v4

      - name: 🛠️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create .env
        run: |
          echo "VITE_URL=${{ secrets.VITE_URL }}" > src/Webs/sinhvien/.env.production
          echo "VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }}" >> src/Webs/sinhvien/.env.production
          echo "VITE_TENANT_ID=${{ secrets.VITE_TENANT_ID }}" >> src/Webs/sinhvien/.env.production
          echo "VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }}" >> src/Webs/sinhvien/.env.production
         
      
      - name: 🏗️ Build and push Docker image gateway service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Webs/sinhvien/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_EDUCATION_SINHVIEN_WEBAPP}}:latest
